# Generated by Django 3.1.5 on 2021-05-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloninventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measure', models.CharField(max_length=24)),
                ('units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amountperunit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('image', models.URLField(null=True)),
                ('prodowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('servowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_other', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person', to=settings.AUTH_USER_MODEL)),
                ('sold_products', models.ManyToManyField(blank=True, related_name='sold_products', to='saloninventory.Products')),
                ('sold_services', models.ManyToManyField(blank=True, related_name='sold_services', to='saloninventory.Services')),
            ],
        ),
    ]
