# Generated by Django 3.1.5 on 2021-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloninventory', '0002_products_sale_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sold_other',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_html',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
